### ISSUE TITLE
模块缺少fileupload和

### ISSUE THREAD

**Issue by coolcoolercool** [MaiSR9527/cloud-openfeign-practice#1]
<module>cloud-openfeign-fileupload-server</module>
        <module>cloud-openfeign-fileupload-client</module>
        master代码中是不是少了，这两个模块？

**Comment by MaiSR9527** [comment]
> ```
>     <module>cloud-openfeign-fileupload-server</module>
>     <module>cloud-openfeign-fileupload-client</module>
>     master代码中是不是少了，这两个模块？
> ```
应该是我之前提交漏了，现在重新提交了，README 也更新了

**Comment by MaiSR9527** [comment]
跳到 文件上传 章节查看
![image](https://github.com/MaiSR9527/cloud-openfeign-practice/assets/38725713/61792a07-b070-4a56-a30c-d073d23d6a86)
